
- name: Add network interface for floating IP
  when: COMMON_FLOATING_INTERFACE_NAME and COMMON_FLOATING_IP
  block:

    - name: Add floating IP as network interface alias
      template:
        src: network/interfaces.d/floating-ip.cfg
        dest: /etc/network/interfaces.d/floating-ip.cfg
        owner: root
        group: root
        mode: 0644

    - name: Ensure floating alias is included in configuration file
      lineinfile:
        dest: /etc/network/interfaces
        state: present
        line: "source /etc/network/interfaces.d/*.cfg"

    - name: Restart networking service
      service:
        name: networking
        state: restarted

    - name: Bring up new interface
      command: "ifup {{ COMMON_FLOATING_INTERFACE_NAME }}"

- name: Add fallback DNS servers to /etc/dhcp/dhclient.conf.
  lineinfile:
     dest: /etc/dhcp/dhclient.conf
     regexp: '^\s*append\s+domain-name-servers'
     line: "append domain-name-servers {{ COMMON_FALLBACK_DNS_SERVERS | join(', ') }};"
  notify: restart networking

- name: Template hosts
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0544

- name: By default allow only ssh
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Set firewall default policy
  ufw:
    state: enabled
    policy: reject
