---

# SANITY ######################################################################

SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 5671
    message: "RabbitMQ does not respond on port 5671."
  - host: localhost
    port: 15671
    message: "RabbitMQ management does not respond on port 15671."

SANITY_CHECK_COMMANDS:
  - command: /usr/sbin/rabbitmqctl node_health_check
    message: "RabbitMQ health check not passing"

# TARSNAP #####################################################################

TARSNAP_BACKUP_FOLDERS: "{{ RABBITMQ_EXPORT_DIR }} /etc/rabbitmq /etc/letsencrypt"
TARSNAP_BACKUP_PRE_SCRIPT: "{{ RABBITMQ_SCRIPTS_DIR }}/{{ RABBITMQ_BACKUP_COMMAND }}"

# CONSUL ######################################################################

consul_service_config:
  services:
    - id: rabbitmq
      name: "rabbitmq"
      tags: ["rabbitmq"]
      port: 5671
      enable_tag_override: true
      checks:
        - name: "Connect to RabbitMQ"
          tcp: "{{ inventory_hostname }}:5671"
          interval: "10m"
    - id: rabbitmq-management
      name: "rabbitmq"
      tags: ["rabbitmq"]
      port: 15671
      enable_tag_override: true
      checks:
        - name: "Connect to RabbitMQ Management Interface"
          tcp: "{{ inventory_hostname }}:15671"
          interval: "10m"

# FILEBEAT ####################################################################

filebeat_prospectors:
  - fields:
      type: "rabbitmq"
    paths:
      - /var/log/rabbitmq/*.log
    multiline:
      pattern: '^='
      match: after
      negate: true
