---

# GENERAL #####################################################################

LOAD_BALANCER_SERVER_IP: "{{ COMMON_FLOATING_IP or ansible_host }}"
COMMON_SERVER_INSTALL_CERTBOT: false
COMMON_SERVER_INSTALL_NODE_EXPORTER: false

# SANITY ######################################################################

SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 80
    message: "Load balancer does not respond on port 80."
  - host: localhost
    port: 443
    message: "Load balancer does not respond on port 443."

# TARSNAP #####################################################################

TARSNAP_BACKUP_FOLDERS: "/etc/letsencrypt /etc/haproxy {{ consul_data_dir }} {{ '/var/lib/nomad' if 'nomad' in group_names else '' }}"

# Consul produces consistent snapshots with these.
TARSNAP_BACKUP_PRE_SCRIPT: "/usr/local/sbin/backup-pre-consul.sh"
TARSNAP_BACKUP_POST_SCRIPT: "/usr/local/sbin/backup-post-consul.sh"

# MAIL ########################################################################

LOAD_BALANCER_OPS_EMAIL: "{{ OPS_EMAIL }}"

# CONSUL ######################################################################

consul_server: true
consul_ui: true
consul_backup: true
consul_service_config:
  services:
    - id: haproxy-http
      name: "haproxy"
      tags: ["haproxy"]
      port: 80
      enable_tag_override: true
      checks:
        - name: "Connect to HAProxy HTTP"
          tcp: "{{ LOAD_BALANCER_SERVER_IP }}:80"
          interval: "10m"
    - id: haproxy-https
      name: "haproxy"
      tags: ["haproxy"]
      port: 443
      enable_tag_override: true
      checks:
        - name: "Connect to HAProxy HTTPS"
          tcp: "{{ LOAD_BALANCER_SERVER_IP }}:443"
          interval: "10m"

# FILEBEAT ####################################################################

filebeat_prospectors:
  - fields:
      type: "haproxy"
    paths:
      - /var/log/haproxy.log
  - fields:
      type: "consul-server"
    paths:
      - /var/log/syslog
    include_lines: ['consul']
  - fields:
      type: "nomad-server"
    paths:
      - /var/log/syslog
    include_lines: ['nomad']
  - fields:
      type: "vault"
    paths:
      - "/var/log/vault/*.log"

# PROMETHEUS ##################################################################

HAPROXY_EXPORTER_ENABLED: true
HAPROXY_EXPORTER_PASSWORD: "{{ NODE_EXPORTER_PASSWORD }}"
