# Note: due to security concerns we prefer using git hashes than ansible versions.

- name: backup-to-tarsnap
  src: https://github.com/open-craft/ansible-backup-to-tarsnap
  version: origin/master

- name: common-server
  src: https://github.com/open-craft/ansible-common-server
  version: origin/master

- name: configure-apt
  src: https://github.com/open-craft/ansible-configure-apt
  version: origin/master

- name: sanity-checker
  src: https://github.com/open-craft/ansible-sanity-checker/
  version: origin/master

- name: forward-server-mail
  src: https://github.com/open-craft/ansible-forward-server-mail
  version: origin/master

- name: backup-swift-container
  src: https://github.com/open-craft/ansible-backup-swift-container
  version: origin/master

- name: dalite
  src: https://github.com/open-craft/ansible-dalite
  version: origin/master

- name: load-balancer
  src: https://github.com/open-craft/ansible-load-balancer
  version: origin/master

- name: rabbitmq
  src: https://github.com/open-craft/ansible-rabbitmq
  version: origin/master

- name: elasticsearch
  src: https://github.com/open-craft/ansible-role-elasticsearch
  version: origin/master

- name: postfix
  src: https://github.com/open-craft/ansible-postfix
  version: origin/master

- name: mattermost
  src: https://github.com/open-craft/ansible-mattermost
  version: origin/master

- name: crafty
  src: https://github.com/open-craft/ansible-crafty
  version: origin/master

- name: link-shortener
  src: https://github.com/open-craft/ansible-link-shortener
  version: origin/master

- name: accounting
  src: https://github.com/open-craft/ansible-accounting
  version: origin/master

- name: mysql
  src: https://github.com/open-craft/ansible-mysql
  version: origin/master

- name: postgres
  src: https://github.com/open-craft/ansible-postgres
  version: origin/master

- name: mongodb
  src: https://github.com/open-craft/ansible-mongodb
  version: origin/master
