# Note: due to security concerns we prefer using git hashes than ansible versions.

- name: backup-to-tarsnap
  src: https://github.com/open-craft/ansible-backup-to-tarsnap
  version: origin/master

- name: common-server
  src: https://github.com/open-craft/ansible-common-server
  version: origin/master

- name: configure-apt
  src: https://github.com/open-craft/ansible-configure-apt
  version: origin/master

- name: sanity-checker
  src: https://github.com/open-craft/ansible-sanity-checker/
  version: origin/master

- name: forward-server-mail
  src: https://github.com/open-craft/ansible-forward-server-mail
  version: origin/master

- name: backup-swift-container
  src: https://github.com/open-craft/ansible-backup-swift-container
  version: origin/master
