---

# GENERAL #####################################################################

MONGODB_OPENSTACK_DB_DEVICE: /dev/vdb1
MONGODB_SERVER_BACKUP_DIR: /var/lib/mongodb/backup

# PROMETHEUS ##################################################################

MONGODB_EXPORTER_ENABLED: true
MONGODB_EXPORTER_VERSION: 1.0.0
MONGODB_EXPORTER_DOWNLOAD_URL: https://github.com/dcu/mongodb_exporter/releases/download/v{{ MONGODB_EXPORTER_VERSION }}/mongodb_exporter-linux-amd64
MONGODB_EXPORTER_PASSWORD: null

MONGODB_EXPORTER_CONSUL_SERVICE:
  service:
    name: mongodb-exporter
    tags:
      - mongodb-exporter
      - monitor-https
    port: 19001
    enable_tag_override: true
