- name: Clone the accounting repository
  git:
    repo: https://github.com/open-craft/accounting.git
    version: master
    dest: "{{ accounting_root_dir }}"
    update: no
  become_user: www-data

- name: Add the `deadsnakes` PPA for getting Python3.6 on Ubuntu 16.04
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'

- name: Install system dependencies for the accounting service
  command: make install_system_dependencies chdir="{{ accounting_root_dir }}"

- name: Install virtualenv for the accounting service
  pip:
    name: virtualenv
    executable: pip3

- name: Install python requirements
  pip:
    requirements: "{{ accounting_root_dir }}/requirements.txt"
    virtualenv: "{{ accounting_virtualenv_dir }}"
    virtualenv_python: python3.6
  become_user: www-data

- name: Install the venv wrapper script
  copy:
    src: venv_exec
    dest: "{{ accounting_virtualenv_dir }}/bin/exec"
    mode: 0755
  become_user: www-data

- name: Install the configuration/environment file for the accounting service
  template:
    src: env.accounting.j2
    dest: "{{ accounting_root_dir }}/.env"
    mode: 0600
  become_user: www-data
