- name: Set login shell for user www-data
  user: name=www-data shell=/bin/bash

- name: Create {{ www_data_home_dir }}
  file: path="{{ www_data_home_dir }}" owner=www-data group=www-data mode=750 state=directory
