---
- name: Create OpenStack volume
  os_volume:
    display_name: "{{ DALITE_LOG_DOWNLOAD_VOLUME_OS_NAME }}"
    display_description: "{{ DALITE_LOG_DOWNLOAD_VOLUME_OS_DESCRIPTION }}"
    state: present
    size: 100
    wait: yes

- name: Connect OpenStack volume to instance
  os_server_volume:
    server: "{{ DALITE_FRONTEND_SERVER_OS_NAME }}"
    volume: "{{ DALITE_LOG_DOWNLOAD_VOLUME_OS_NAME }}"
    device: "{{ DALITE_LOG_DOWNLOAD_VOLUME_DEVICE_ID }}"
    state: present
    wait: yes

- name: format log download volume
  filesystem:
    dev: "{{ DALITE_LOG_DOWNLOAD_VOLUME_DEVICE_ID }}"
    fstype: "{{ DALITE_LOG_DOWNLOAD_VOLUME_FILESYSTEM }}"
    resizefs: yes

- name: mount log download volume
  mount:
    src: "{{ DALITE_LOG_DOWNLOAD_VOLUME_DEVICE_ID }}"
    name: "{{ DALITE_LOG_DOWNLOAD_USER_HOME }}"
    state: mounted
