---
- name: install passlib for htpasswd generation
  apt:
    name: python-passlib

- name: generate htpasswd file for the Prometheus node exporter
  htpasswd:
    path: "{{ NODE_EXPORTER_HTPASSWD_PATH }}"
    username: node-exporter
    password: "{{ NODE_EXPORTER_PASSWORD }}"

- name: set up nginx to reverse-proxy the Prometheus node exporter
  template:
    src: nginx-node-exporter.j2
    dest: "{{ NODE_EXPORTER_NGINX_CONFIG_PATH }}"
  notify:
    - reload nginx

- name: enable nginx site configuration
  file:
    src: "{{ NODE_EXPORTER_NGINX_CONFIG_PATH }}"
    dest: /etc/nginx/sites-enabled/node-exporter
    state: link
  notify:
    - reload nginx

- name: allow Prometheus metrics collections
  ufw:
    rule: allow
    port: 19100
    proto: tcp

- name: create Consul config directory
  file:
    path: /etc/consul
    state: directory

- name: create Consul service definition file
  copy:
    content: "{{ NODE_EXPORTER_CONSUL_SERVICE | to_nice_json }}"
    dest: /etc/consul/node-exporter.json
  notify:
    - reload consul
