---
# tasks file for sanity-check
- name: copy sanity check script
  copy: src=sanity_check.py dest={{ SANITY_CHECK_SCRIPT_LOCATION }} mode=500

- name: copy sanity check config
  copy:
    content: "{{ sanity_check_control_file|to_json }}"
    dest: "{{ SANITY_CHECK_CONFIG }}"
    mode: "400"


- name: install sanity checks crontab
  cron:
    job: "{{ SANITY_CHECK_SCRIPT_LOCATION }} {{ SANITY_CHECK_CONFIG }} > /dev/null 2>&1"
    minute: "10,20,30,40,50"
    name: "sanity checker for: {{ SANITY_CHECK_SUBJECT }}"

- name: Run sanity check
  command: "{{ SANITY_CHECK_SCRIPT_LOCATION }} {{ SANITY_CHECK_CONFIG }}"