---
- name: install dependencies
  apt: name={{ item }} state=present
  with_items: "{{ BACKUP_SWIFT_CONTAINER_DEPS }}"

- name: create backup dir
  file: name="{{ BACKUP_SWIFT_LOCAL_DIR }}" state=directory mode="0700"

- name: save pre backup script
  template:
    src: backup-swift-pre.sh
    dest: "{{ BACKUP_SWIFT_PRE_DEST }}"
    owner: "root"
    mode: "0700"

- name: save local rc
  copy:
    content: "{{ BACKUP_SWIFT_RC }}"
    dest: "{{ BACKUP_SWIFT_RC_DEST }}"
    mode: "0500"
    owner: "root"
