- name: Copy nginx site configuration
  template: src=opencraft-nginx.j2 dest=/etc/nginx/sites-available/opencraft

- name: Enable nginx site configuration
  file: src=/etc/nginx/sites-available/opencraft dest=/etc/nginx/sites-enabled/opencraft state=link

- name: Copy SSL certificate
  copy: content="{{ OPENCRAFT_SSL_CERT }}" dest=/etc/ssl/certs/ssl-cert.pem group=ssl-cert mode=640

- name: Copy SSL key
  copy: content="{{ OPENCRAFT_SSL_KEY }}" dest=/etc/ssl/private/ssl-cert.key group=ssl-cert mode=640

- name: Copy websocket SSL certificate
  copy: content="{{ OPENCRAFT_WEBSOCKET_SSL_CERT }}" dest=/etc/ssl/certs/ssl-websocket-cert.pem group=ssl-cert mode=640

- name: Copy websocket SSL key
  copy: content="{{ OPENCRAFT_WEBSOCKET_SSL_KEY }}" dest=/etc/ssl/private/ssl-websocket-cert.key group=ssl-cert mode=640

- name: Restart nginx
  service: name=nginx state=restarted

- name: Open HTTP port on the firewall
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 80
    - 443
