- name: Copy nginx site configuration
  template:
    src: accounting-nginx.j2
    dest: /etc/nginx/sites-available/accounting

- name: Enable nginx site configuration
  file:
    src: /etc/nginx/sites-available/accounting
    dest: /etc/nginx/sites-enabled/accounting
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted
