---

vault_config_dir: "/etc/vault"
vault_policy_dir: "{{ vault_config_dir }}/policies"
vault_tls_dir: "{{ vault_config_dir }}/tls"

vault_policy_mgmt_token: null

# Example:
#
# vault_policies:
#   - name: policy-management
#     policy:
#       path:
#         "sys/policy":
#           capabilities:
#             - create
#             - read
#             - update
#             - list
#             - delete
#   - name: full-secret
#     policy:
#       path:
#         "secret/*":
#           capabilities:
#             - create
#             - read
#             - update
#             - list
#             - delete
#   - name: full-accounting
#     policy:
#       path:
#         "accounting/*":
#           capabilities:
#             - create
#             - read
#             - update
#             - list
#             - delete
#   - name: full-bizdev
#     policy:
#       path:
#         "bizdev/*":
#           capabilities:
#             - create
#             - read
#             - update
#             - list
#             - delete
#   - name: add-github-users
#     policy:
#       path:
#         "identity/entity*":
#           capabilities:
#             - create
#             - read
#             - update
#             - list
#             - delete
#         "sys/auth":
#           capabilities:
#             - read
#             - list
#   - name: some-specific-newcomer
#     policy:
#       path:
#         "secret/secret-this-newcomer-needs":
#           capabilities:
#             - read
#
vault_policies: []
