---

# GENERAL #####################################################################

COMMON_SERVER_NO_BACKUPS: true

# SANITY ######################################################################

SANITY_CHECK_LIVE_PORTS:
  - host: localhost
    port: 443
    message: "Cannot connect to HTTPS port."
  - host: localhost
    port: 1786
    message: "Accounting API is not responding on port 1786."
