---

- name: Log in to Vault
  shell: |
    vault login -token-only \
      -ca-cert={{ vault_tls_dir }}/ca.pem \
      -client-key={{ vault_tls_dir }}/key.pem \
      -client-cert={{ vault_tls_dir }}/cert.pem \
      {{ vault_policy_mgmt_token }}
  no_log: true

- name: Copy Vault policies to the server
  copy:
    content: "{{ item.policy }}"
    dest: "{{ vault_policy_dir }}/{{ item.name }}.json"
  with_items: "{{ vault_policies }}"

- name: Write Vault policies
  shell: |
    vault policy write \
      -ca-cert={{ vault_tls_dir }}/ca.pem \
      -client-key={{ vault_tls_dir }}/key.pem \
      -client-cert={{ vault_tls_dir }}/cert.pem \
      {{ item.name }} \
      {{ vault_policy_dir }}/{{ item.name }}.json
  with_items: "{{ vault_policies }}"
