---
- name: Create consul group
  group:
    name: consul
    system: yes

- name: Create consul user
  user:
    name: consul
    group: consul
    createhome: no
    system: yes

- name: Mount "{{ consul_data_dir }}"
  mount:
    name: "{{ consul_data_dir }}"
    src: "{{ consul_openstack_data_device }}"
    fstype: ext4
    state: mounted
  when: consul_server

- name: Create consul directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: consul
    mode: 0750
  with_items:
    - { path: "{{ consul_config_dir }}", owner: root }
    - { path: "{{ consul_data_dir }}", owner: consul }

- name: Download and unarchive the Consul binary
  unarchive:
    src: "{{ consul_url }}"
    dest: "{{ consul_bin_dir }}"
    owner: consul
    group: consul
    remote_src: yes
    creates: "{{ consul_bin_dir }}/consul"

- name: Create Consul configuration file
  template:
    src: config.json.j2
    dest: "{{ consul_config_dir }}/config.json"
    group: consul
  notify: restart consul

- name: Create Consul service definition file
  copy:
    content: "{{ consul_service_config | to_nice_json }}"
    dest: "{{ consul_config_dir }}/service.json"
    group: consul
  when: consul_service_config != ""
  notify: restart consul

- name: Create Consul systemd service file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: Enable and start systemd service to start on boot automatically
  systemd:
    name: consul.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Open TCP/UDP ports on firewall needed for Consul RPC/gossip
  ufw:
    rule: allow
    port: '8300:8302'
    proto: "{{ item }}"
  with_items:
    - tcp
    - udp

- name: Copy pre- and post-backup scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0500
  with_items:
  - { src: backup-pre-consul.sh, dest: /usr/local/sbin/backup-pre-consul.sh }
  - { src: backup-post-consul.sh, dest: /usr/local/sbin/backup-post-consul.sh }
  when: consul_backup
