---
- name: Set up Consul Connect proxy endpoints for memcached and Redis
  template:
    src: consul-connect.service.j2
    dest: /etc/systemd/system/consul-connect.service
  vars:
    upstream_specs: "{{ consul_connect_memcached_upstream_specs }}{{ consul_connect_redis_upstream_specs }}"

- name: Start and enable the Consul Connect proxy
  systemd:
    name: consul-connect.service
    enabled: true
    state: started
