- name: create crafty group
  group:
    name: crafty

- name: create crafty user
  user:
    name: crafty
    group: crafty
    home: "{{ CRAFTY_HOME }}"

- name: check out source code
  git:
    repo: "{{ CRAFTY_REPO }}"
    version: "{{ CRAFTY_BRANCH }}"
    dest: "{{ CRAFTY_HOME }}/crafty"
  become_user: crafty

- name: Install virtualenv package
  apt:
    name: virtualenv

- name: install requirements
  pip:
    requirements: "{{ CRAFTY_HOME }}/crafty/requirements.txt"
    virtualenv: "{{ CRAFTY_HOME }}/venvs/crafty"
    virtualenv_python: python3
  become_user: crafty

- name: create systemd service
  template:
    src: crafty.service.j2
    dest: /etc/systemd/system/crafty.service

- name: start and enable the crafty service
  service:
    name: crafty
    state: started
    enabled: yes
