---
- name: Set login shell for user {{ www_user }}
  user:
    name: "{{ www_user }}"
    shell: /bin/bash

- name: Create {{ www_data_home_dir }}
  file:
    path: "{{ www_data_home_dir }}"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"
    mode: 0750
    state: directory

- name: Copy shell configuration for user {{ www_user }}
  template:
    src: bashrc
    dest: "{{ www_data_home_dir }}/.bashrc"
    owner: "{{ www_user }}"
    group: "{{ www_group }}"

- name: Clone the opencraft repository
  git:
    repo: https://github.com/open-craft/opencraft.git
    dest: "{{ opencraft_root_dir }}"
    update: no
  become_user: "{{ www_user }}"

- name: Install the configuration/environment file
  template:
    src: env.j2
    dest: "{{ opencraft_root_dir }}/.env"
    mode: 0600
    backup: yes
  become_user: "{{ www_user }}"

- import_tasks: common.yml

- name: Install the venv wrapper script
  copy:
    src: venv_exec
    dest: "{{ opencraft_virtualenv_dir }}/bin/exec"
    mode: 0755
  become_user: "{{ www_user }}"

- name: "Create directory {{ www_data_home_dir }}/.ssh"
  file:
    path: "{{ www_data_home_dir }}/.ssh"
    state: directory
  become_user: "{{ www_user }}"

- name: Install the SSH private key used for deploying instances.
  copy:
    content: "{{ OPENCRAFT_OPENSTACK_SSH_KEY }}"
    dest: "{{ www_data_home_dir }}/.ssh/id_rsa"
    mode: 0600
  become_user: "{{ www_user }}"

- name: Copy nginx site configuration
  template:
    src: opencraft-nginx.j2
    dest: /etc/nginx/sites-available/opencraft
  notify:
    - restart nginx

- name: Enable nginx site configuration
  file:
    src: /etc/nginx/sites-available/opencraft
    dest: /etc/nginx/sites-enabled/opencraft
    state: link
  notify:
    - restart nginx

- name: Copy SSL certificate
  copy:
    content: "{{ OPENCRAFT_SSL_CERT }}"
    dest: /etc/ssl/certs/ssl-cert.pem
    group: ssl-cert
    mode: 0640
  notify:
    - restart nginx

- name: Copy SSL key
  copy:
    content: "{{ OPENCRAFT_SSL_KEY }}"
    dest: /etc/ssl/private/ssl-cert.key
    group: ssl-cert
    mode: 0640
  notify:
    - restart nginx

- name: Copy websocket SSL certificate
  copy:
    content: "{{ OPENCRAFT_WEBSOCKET_SSL_CERT }}"
    dest: /etc/ssl/certs/ssl-websocket-cert.pem
    group: ssl-cert
    mode: 0640
  notify:
    - restart nginx

- name: Copy websocket SSL key
  copy:
    content: "{{ OPENCRAFT_WEBSOCKET_SSL_KEY }}"
    dest: /etc/ssl/private/ssl-websocket-cert.key
    group: ssl-cert
    mode: 0640
  notify:
    - restart nginx

- name: Copy screen session configuration
  template:
    src: "ocim-screenrc"
    dest: "{{ opencraft_screenrc_path }}"
    owner: "{{ session_user }}"
    group: "{{ session_user_group }}"

- name: Copy systemd service file
  template:
    src: "ocim-screen.service"
    dest: "/etc/systemd/system/ocim-screen.service"

- name: Enable and start systemd service to start on boot automatically
  systemd:
    daemon-reload: yes
    name: ocim-screen.service
    enabled: yes
    state: started

- name: Open HTTP port on the firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443

- import_tasks: configure-swift-backups.yml
  when: OPENCRAFT_BACKUP_SWIFT_ENABLED
