---
- name: Create mongodb group
  group:
    name: mongodb
    system: yes

- name: Create mongodb user
  user:
    name: mongodb
    group: mongodb
    home: /var/lib/mongodb
    system: yes

- name: mount /var/lib/mongodb
  mount:
    name: /var/lib/mongodb
    src: "{{ MONGODB_OPENSTACK_DB_DEVICE }}"
    fstype: ext4
    state: mounted

- name: mkdir /var/lib/mongodb/{db,log}
  file:
    path: "/var/lib/mongodb/{{ item }}"
    state: directory
    mode: 0750
    owner: mongodb
    group: mongodb
  with_items:
    - db
    - log

- name: chown -R /var/lib/mongodb
  file:
    path: /var/lib/mongodb
    owner: mongodb
    group: mongodb
    recurse: yes
    state: directory

- name: chmod /var/lib/mongodb
  file:
    path: /var/lib/mongodb
    mode: 0700
    state: directory

- name: Open MongoDB port on the firewall
  ufw:
    rule: allow
    port: 27017
    proto: tcp

- name: configure log rotation for the MongoDB log
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/mongodb.conf
    mode: 0644

- name: Copy pre-backup script
  template:
    src: backup-pre-mongodb.sh
    dest: /usr/local/sbin/backup-pre.sh
    mode: 0500

- name: Copy post-backup script
  template:
    src: backup-post-mongodb.sh
    dest: /usr/local/sbin/backup-post.sh
    mode: 0500

- name: Install Prometheus MongoDB exporter
  when: MONGODB_EXPORTER_ENABLED
  block:

    - name: Download MongoDB exporter
      get_url:
        url: "{{ MONGODB_EXPORTER_DOWNLOAD_URL }}"
        dest: /usr/local/bin/mongodb_exporter
        mode: 0755

    - name: Create MongoDB exporter environment file
      copy:
        content: |
          MONGODB_URL=mongodb://{{ mongodb_root_admin_name }}:{{ mongodb_root_admin_password }}@localhost:27017
        dest: /etc/mongodb_exporter.conf
        mode: 0640
        owner: root
        group: mongodb

    - name: Copy MongoDB exporter service definition
      copy:
        src: mongodb_exporter.service
        dest: /etc/systemd/system/mongodb_exporter.service

    - name: Start MongoDB exporter
      systemd:
        daemon-reload: yes
        name: mongodb_exporter.service
        state: started
        enabled: yes

    - name: Create Consul service definition file
      copy:
        content: "{{ MONGODB_EXPORTER_CONSUL_SERVICE | to_nice_json }}"
        dest: /etc/consul/mongodb-exporter.json
      notify:
        - reload consul
