---
- name: Create mongodb group
  group:
    name: mongodb
    system: yes

- name: Create mongodb user
  user:
    name: mongodb
    group: mongodb
    home: "{{ MONGODB_HOME }}"
    system: yes

- name: Mount MongoDB home
  mount:
    name: "{{ MONGODB_HOME }}"
    src: "{{ MONGODB_OPENSTACK_DB_DEVICE }}"
    fstype: ext4
    state: mounted

- name: Create db and log directories for MongoDB home
  file:
    path: "{{ MONGODB_HOME }}/{{ item }}"
    state: directory
    mode: 0750
    owner: mongodb
    group: mongodb
  with_items:
    - db
    - log

- name: Change MongoDB Home owner
  file:
    path: "{{ MONGODB_HOME }}"
    owner: mongodb
    group: mongodb
    recurse: yes
    state: directory

- name: Change MongoDB permissions
  file:
    path: "{{ MONGODB_HOME }}"
    mode: 0700
    state: directory

- name: Open MongoDB port on the firewall
  ufw:
    rule: allow
    port: 27017
    proto: tcp

- name: configure log rotation for the MongoDB log
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/mongodb.conf
    mode: 0644

- name: Copy pre-backup script
  template:
    src: backup-pre-mongodb.sh
    dest: /usr/local/sbin/backup-pre.sh
    mode: 0500

- name: Copy post-backup script
  template:
    src: backup-post-mongodb.sh
    dest: /usr/local/sbin/backup-post.sh
    mode: 0500

- name: Install Prometheus MongoDB exporter
  when: MONGODB_EXPORTER_ENABLED
  block:
    - name: Install golang package
      apt:
        name:
          - golang
        update_cache: yes

    - name: Download MongoDB exporter
      git:
        repo: "{{ MONGODB_EXPORTER_REPO }}"
        dest: "{{ MONGODB_EXPORTER_PATH }}"
        version: "{{ MONGODB_EXPORTER_VERSION }}"

    - name: Compile MongoDB exporter files
      make:
        chdir: "{{ MONGODB_EXPORTER_PATH }}"
        target: build
      environment:
        GOPATH: "{{ GO_PATH }}"

    - name: create symlink to exporter binary
      file:
        src: "{{ MONGODB_EXPORTER_PATH }}/mongodb_exporter"
        dest: /usr/local/bin/mongodb_exporter
        state: link
        force: yes
        owner: mongodb
        group: mongodb
        mode: 0755

    - name: Create MongoDB exporter environment file
      copy:
        content: |
          MONGODB_URL=mongodb://{{ mongodb_root_admin_name }}:{{ mongodb_root_admin_password }}@localhost:27017
        dest: /etc/mongodb_exporter.conf
        mode: 0640
        owner: root
        group: mongodb

    - name: Copy MongoDB exporter service definition
      copy:
        src: mongodb_exporter.service
        dest: /etc/systemd/system/mongodb_exporter.service

    - name: Start MongoDB exporter
      systemd:
        daemon-reload: yes
        name: mongodb_exporter.service
        state: started
        enabled: yes

    - name: Create Consul service definition file
      copy:
        content: "{{ MONGODB_EXPORTER_CONSUL_SERVICE | to_nice_json }}"
        dest: /etc/consul/mongodb-exporter.json
      notify:
        - reload consul
