---
# Playbook to set up common services on Open edX appservers.  These services run after setting up
# Open edX: The node-exporter role depends on nginx already being installed.  The filebeat role
# reuses Elastic packages installed by the edx-configuration playbook.

- name: Set up common services on Open edX appservers – finalization
  hosts: app
  become: true
  roles:
    - role: node-exporter
      when: NODE_EXPORTER_PASSWORD is not none
    - role: filebeat
      # Appservers may have some Elastic stuff already installed on them.
      filebeat_elastic_apt_pin: 200
      when: filebeat_logstash_hosts | length > 0
