---
# Playbook for setting up a Backup Pruner server.

- name: Install and set up the backup-pruner server
  hosts: backup-pruner
  become: true
  roles:
    - common-server
    - pmbauer.tarsnap
    - backup-pruner
