---
# Playbook for setting up an Elasticsearch server.

- name: Set up elasticsearch servers
  hosts: elasticsearch
  become: true
  roles:
    - common-server
    - forward-server-mail
    - elasticsearch
