---
## This playbook deploys hxat, catchpy and loris roles.

# Apply common configuration to all hosts

- hosts: catchpy:hxat:loris
  
  roles:
    # The recommended configuration for these tools involved using apache2.
    # Our common-server role includes common-server-init, which installs nginx and can conflict with apache2.
    # TODO: Consider using nginx for hxat/catchpy/loris. Or add common-server here to get the rest of features (consul, …)
    # For now, instead of using common-server we manually add the features we need, e.g. tarsnap for backups
    # The common-apache2 role also installs certbot
    - role: common-apache2

# Configure and deploy catchpy servers.
- hosts: catchpy

  roles:
    - role: tarsnap
      # FIXME add DB dumper script
      TARSNAP_KEY: "{{ HXAT_PRODUCTION_RW_TARSNAP_KEY }}"
      TARSNAP_BACKUP_FOLDERS: "{{ FIXME_ADD_SOME__DOWNLOAD_LOG_DIR }} {{ SOME_LOG_DOWNLOAD_DB_DIR }}"
    - role: catchpy
      vars:
        ansible_python_interpreter: /usr/bin/python2
  tags:
    - catchpy

# Configure and deploy hxat servers.
- hosts: hxat

  roles:
    - role: tarsnap
      # FIXME add DB dumper script
      TARSNAP_KEY: "{{ CATCHPY_PRODUCTION_RW_TARSNAP_KEY }}"
      TARSNAP_BACKUP_FOLDERS: "{{ FIXME_ADD_SOME__DOWNLOAD_LOG_DIR }} {{ SOME_LOG_DOWNLOAD_DB_DIR }}"
    - role: hxat
      vars:
        ansible_python_interpreter: /usr/bin/python2
  tags:
    - hxat

# Configure and deploy loris servers.
- hosts: loris

  roles:
    # loris DB/images not backed up with tarsnap since no courses use image annotations yet

    - role: loris
      vars:
        ansible_python_interpreter: /usr/bin/python2
  
  tags:
    - loris
