---
# Playbook for setting up a HAProxy load balancing server.

- name: Set up load-balancing servers
  hosts: load-balancer
  become: true
  roles:
    - common-server
    - load-balancer
    - node-exporter
