---
# Playbook for setting up a MongoDB server.

- name: Set up MongoDB servers
  hosts: mongodb
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: mongodb
      tags: 'mongodb'

    - role: greendayonfire.mongodb
      tags: 'greendayonfire.mongodb'
