---
- name: Deploy the OpenCraft Instance Manager
  hosts: ocim
  become: true
  roles:
    - role: common-server
      tags: 'common-server'

    - role: ocim
      tags: 'ocim'

    - role: node-exporter
      tags: 'node-exporter'
