---
appserver_instance_id: null

# The local ports that will be tunnelled to memcached and redis-sentinel.
appserver_memcached_ports:
  - 11211
  - 11212
  - 11213
appserver_redis_sentinel_ports:
  - 6379
  - 6380
  - 6381

# Build upstream specs for the Consul Connect command line.
appserver_memcached_upstream_specs: |-
  {% for port in appserver_memcached_ports %} -upstream memcached-{{ appserver_instance_id }}-{{ loop.index0 }}:{{ port }}{% endfor %}
appserver_redis_sentinel_upstream_specs: |-
  {% for port in appserver_redis_sentinel_ports %} -upstream redis-sentinel-{{ appserver_instance_id }}-{{ loop.index0 }}:{{ port }}{% endfor %}
